/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myprojcet.sdaproject.Component1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author asus
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDocumentView = new javax.swing.JTextArea();
        jButtonFileImport = new javax.swing.JButton();
        jButtonAnalyze = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Document Analyzer");

        jTextAreaDocumentView.setColumns(20);
        jTextAreaDocumentView.setRows(10);
        jScrollPane1.setViewportView(jTextAreaDocumentView);

        jButtonFileImport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonFileImport.setText("Import");
        jButtonFileImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileImportActionPerformed(evt);
            }
        });

        jButtonAnalyze.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAnalyze.setText("Analyze");
        jButtonAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyzeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFileImport, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButtonAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFileImport, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButtonAnalyze.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileImportActionPerformed

        try {
            //choosing files
            ImportDocument();
        } catch (InvalidFormatException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFileImportActionPerformed

    private void jButtonAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyzeActionPerformed

        close();
        //create TimePrediction object
        TimePrediction prediction = new TimePrediction();
        prediction.setVisible(true);
    }//GEN-LAST:event_jButtonAnalyzeActionPerformed

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    public void ImportDocument() throws InvalidFormatException, IOException {

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(".\\src\\main\\java\\com\\myprojcet\\sdaproject\\Component1"));
        int result = fileChooser.showOpenDialog(this);
        java.util.List<String> documentArray = new ArrayList<>();
        File selectedFile = fileChooser.getSelectedFile();

        //Assign values to JtextArea
        if (result == JFileChooser.APPROVE_OPTION) {
            System.out.println("File path " + selectedFile.getAbsolutePath());

            BufferedReader buffer = new BufferedReader(new FileReader(selectedFile));
            String lines = buffer.readLine();

            while (lines != null) {
                documentArray.add(lines);
                jTextAreaDocumentView.append(lines + "\n");
                jTextAreaDocumentView.setEditable(false);
                lines = buffer.readLine();

            }
            String intro = "Introduction";
            System.out.println("Into index " + documentArray.indexOf(intro));

            String problem = "Problem";
            System.out.println("Problem index " + documentArray.indexOf(problem));

            String Solution = "Solution";
            System.out.println("Solution index " + documentArray.indexOf(Solution));

            String Functionality = "Functionality";
            System.out.println("Functionality index " + documentArray.indexOf(Functionality));

            String Profile = "Team profile";
            System.out.println("Profile index " + documentArray.indexOf(Profile));

            //seperate introduction
            java.util.List<String> introPara = documentArray.subList(3, 4);
            for (String line : introPara) {

                System.out.println(line);
            }

            System.out.println("-------------------------------");
            //seperate problem     
            java.util.List<String> proPara = documentArray.subList(5, 6);
            for (String line : proPara) {

                System.out.println(line);
            }
            System.out.println("-------------------------------");
            //seperate Solution     
            java.util.List<String> solutionPara = documentArray.subList(7, 8);
            for (String line : solutionPara) {

                System.out.println(line);
            }

            System.out.println("-------------------------------");
            //seperate Functionality     
            java.util.List<String> functionalityPara = documentArray.subList(9, 10);
            for (String line : functionalityPara) {

                System.out.println(line);

                FileOutputStream out = new FileOutputStream(".\\src\\main\\java\\com\\myprojcet\\sdaproject\\Component1\\\\Functionalitiy.txt");

                out.write(line.getBytes());
                out.close();

            }

        }

    }

    //Textfile Creation
    public void getTextFilePath() throws IOException {

        String data = "Test data";

        FileOutputStream out = new FileOutputStream("G:\\SLIIT Academic stuff\\4th Year SEM1\\CDAP\\Integration_process\\sdaproject\\src\\main\\resources\\\\Functionalitiy.txt");

        out.write(data.getBytes());
        out.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalyze;
    private javax.swing.JButton jButtonFileImport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDocumentView;
    // End of variables declaration//GEN-END:variables
}
