/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myprojcet.sdaproject.Component2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class EmployeeUi extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeUi
     */
    private String empNum, pensionEmp, epfEmp, insuranceEmp;
    
    
    public EmployeeUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        epf = new javax.swing.JComboBox<>();
        pension = new javax.swing.JComboBox<>();
        scaleEmp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        classDiagEmp = new javax.swing.JCheckBox();
        eRDiagEmp = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        insurance = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Availability of Pension");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Required diagrams");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Insurance for dependents");

        epf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        epf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Available", "Not Available" }));
        epf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfActionPerformed(evt);
            }
        });

        pension.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Available", "Not Available" }));
        pension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensionActionPerformed(evt);
            }
        });

        scaleEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scaleEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "<100", "<1000", ">=1000" }));
        scaleEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleEmpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Management System diagrams");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Availability of EPF");

        classDiagEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        classDiagEmp.setText("Class Diagram");
        classDiagEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classDiagEmpActionPerformed(evt);
            }
        });

        eRDiagEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eRDiagEmp.setText("ER diagram");
        eRDiagEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eRDiagEmpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Number of Employees");

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        insurance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Given", "Not Given" }));
        insurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(scaleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(epf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pension, 0, 340, Short.MAX_VALUE)
                                        .addComponent(insurance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(classDiagEmp)
                                            .addGap(18, 18, 18)
                                            .addComponent(eRDiagEmp))))))))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scaleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pension, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classDiagEmp)
                    .addComponent(eRDiagEmp))
                .addGap(35, 35, 35)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classDiagEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classDiagEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classDiagEmpActionPerformed

    private void eRDiagEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eRDiagEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eRDiagEmpActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(classDiagEmp.isSelected()){
        
            try {
                employeeClassDiagBuild();
            } catch (IOException ex) {
                Logger.getLogger(EmployeeUi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(eRDiagEmp.isSelected()){
            
            
        }
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new DiagramUi().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void scaleEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleEmpActionPerformed
        // TODO add your handling code here:
        empNum = scaleEmp.getItemAt(scaleEmp.getSelectedIndex());
    }//GEN-LAST:event_scaleEmpActionPerformed

    private void epfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfActionPerformed
        // TODO add your handling code here:
        epfEmp = epf.getItemAt(epf.getSelectedIndex());
    }//GEN-LAST:event_epfActionPerformed

    private void pensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensionActionPerformed
        // TODO add your handling code here:
        pensionEmp = pension.getItemAt(pension.getSelectedIndex());
    }//GEN-LAST:event_pensionActionPerformed

    private void insuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceActionPerformed
        // TODO add your handling code here:
        insuranceEmp = insurance.getItemAt(insurance.getSelectedIndex());
        
    }//GEN-LAST:event_insuranceActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JCheckBox classDiagEmp;
    private javax.swing.JCheckBox eRDiagEmp;
    private javax.swing.JComboBox<String> epf;
    private javax.swing.JComboBox<String> insurance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> pension;
    private javax.swing.JComboBox<String> scaleEmp;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    public void employeeClassDiagBuild() throws IOException{
        
        DisplayImage display = new DisplayImage();
        
        if(empNum.equalsIgnoreCase("<100")){
        
           if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){
               
               display.displayImg("C:/UML/employee/Class/4.jpg");
           }
           else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Not Given")){

                display.displayImg("C:/UML/employee/Class/3.jpg");
           }
           else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){

                display.displayImg("C:/UML/employee/Class/5.jpg");
           }
           else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Given")){

                display.displayImg("C:/UML/employee/Class/6.jpg");
           }
           else{
               JOptionPane.showMessageDialog(null, "Requirements insufficient for diagram generation",
                        "Diagram not found", JOptionPane.PLAIN_MESSAGE);
           }
               
        }else if(empNum.equalsIgnoreCase("<1000")){
            
            if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){
                 
               display.displayImg("C:/UML/employee/Class/7.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
            
                display.displayImg("C:/UML/employee/Class/8.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Given")){
            
               display.displayImg("C:/UML/employee/Class/9.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
            
                display.displayImg("C:/UML/employee/Class/10.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){
            
                display.displayImg("C:/UML/employee/Class/11.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
                
                display.displayImg("C:/UML/employee/Class/12.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Given")){
                
                display.displayImg("C:/UML/employee/Class/13.jpg");
            }
            else{
            
                 display.displayImg("C:/UML/employee/Class/14.jpg");
            }
        }else{
            if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){
                 
                display.displayImg("C:/UML/employee/Class/15.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
            
                display.displayImg("C:/UML/employee/Class/16.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Given")){
            
                display.displayImg("C:/UML/employee/Class/17.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
            
                display.displayImg("C:/UML/employee/Class/18.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Given")){
            
                display.displayImg("C:/UML/employee/Class/19.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Available") && insuranceEmp.equalsIgnoreCase("Not Given")){
            
                display.displayImg("C:/UML/employee/Class/20.jpg");
            }
            else if(epfEmp.equalsIgnoreCase("Not Available") && pensionEmp.equalsIgnoreCase("Not Available") && insuranceEmp.equalsIgnoreCase("Given")){
            
                display.displayImg("C:/UML/employee/Class/21.jpg");
            }
            else{
                
                display.displayImg("C:/UML/employee/Class/22.jpg");
            }
            
        }
    }
    
    
}
