
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myprojcet.sdaproject.Component2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class HotelUi extends javax.swing.JFrame {

    /**
     * Creates new form HotelUi
     */
    private String scaleHotel, restaurantsHotel, flightHotel, taxiHotel; 
            
            
    public HotelUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        restaurants = new javax.swing.JComboBox<>();
        flight = new javax.swing.JComboBox<>();
        scale = new javax.swing.JComboBox<>();
        classDiag = new javax.swing.JCheckBox();
        eRDiag = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        taxi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hotel Management System diagrams");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Availability of Restaurants");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Scale of hotel");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Availability of Flight booking");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Required diagrams");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Availability of Taxi reservation");

        restaurants.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        restaurants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Available", "Not Available" }));
        restaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantsActionPerformed(evt);
            }
        });

        flight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Available", "Not Available" }));
        flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightActionPerformed(evt);
            }
        });

        scale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Small", "Medium", "Large" }));
        scale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleActionPerformed(evt);
            }
        });

        classDiag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        classDiag.setText("Class Diagram");

        eRDiag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eRDiag.setText("ER diagram");

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        taxi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Available", "Not Available" }));
        taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(restaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scale, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(flight, 0, 340, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(classDiag)
                                        .addGap(18, 18, 18)
                                        .addComponent(eRDiag))
                                    .addComponent(taxi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scale, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(taxi))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classDiag)
                    .addComponent(eRDiag))
                .addGap(54, 54, 54)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(classDiag.isSelected()){
        
            try {
                hotelClassDiagBuild();
            } catch (IOException ex) {
                Logger.getLogger(HotelUi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(eRDiag.isSelected()){
            
            if(eRDiag.isSelected()){
        
                //hotelERDiagBuild();
            }
            
        }
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new DiagramUi().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void scaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleActionPerformed
        // TODO add your handling code here:
        scaleHotel = scale.getItemAt(scale.getSelectedIndex());
        if(scaleHotel.equalsIgnoreCase("small")){
            
            flight.setVisible(false);
            taxi.setVisible(false);  
            jLabel5.setVisible(false);
            jLabel7.setVisible(false);
            
        }else if(scaleHotel.equalsIgnoreCase("medium")){
            
            flight.setVisible(false);
            jLabel5.setVisible(false);
            taxi.setVisible(true);
            jLabel7.setVisible(true);
        }
        else{
            
            flight.setVisible(true);
            taxi.setVisible(true);  
            jLabel5.setVisible(true);
            jLabel7.setVisible(true);
        }
    }//GEN-LAST:event_scaleActionPerformed

    private void restaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantsActionPerformed
        // TODO add your handling code here:
        restaurantsHotel = restaurants.getItemAt(restaurants.getSelectedIndex());
    }//GEN-LAST:event_restaurantsActionPerformed

    private void flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightActionPerformed
        // TODO add your handling code here:
        flightHotel = flight.getItemAt(flight.getSelectedIndex());
    }//GEN-LAST:event_flightActionPerformed

    private void taxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxiActionPerformed
        // TODO add your handling code here:
        taxiHotel = taxi.getItemAt(taxi.getSelectedIndex());
    }//GEN-LAST:event_taxiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JCheckBox classDiag;
    private javax.swing.JCheckBox eRDiag;
    private javax.swing.JComboBox<String> flight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> restaurants;
    private javax.swing.JComboBox<String> scale;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> taxi;
    // End of variables declaration//GEN-END:variables


     public void hotelClassDiagBuild() throws IOException{
        
        DisplayImage display = new DisplayImage();
        
        if(scaleHotel.equalsIgnoreCase("small")){
        
            
           if(restaurantsHotel.equalsIgnoreCase("Available")){
               
                display.displayImg("C:/UML/hotel/Class/2.jpg");
           }
           else if(restaurantsHotel.equalsIgnoreCase("Not Available")){

                display.displayImg("C:/UML/hotel/Class/4.png");
           }
           else{
               JOptionPane.showMessageDialog(null, "Requirements insufficient for diagram generation",
                        "Diagram not found", JOptionPane.PLAIN_MESSAGE);
           }
               
        }else if(scaleHotel.equalsIgnoreCase("medium")){
            
            if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available")){
                 
                display.displayImg("C:/UML/hotel/Class/5.jpg");
            }
            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available")){
            
                display.displayImg("C:/UML/hotel/Class/6.jpg");
            }
            else{
                 display.displayImg("C:/UML/hotel/Class/4.png");
            }
        }else{
            
            if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available") && flightHotel.equalsIgnoreCase("Available")){
                 
                display.displayImg("C:/UML/hotel/Class/7.jpg");
            }
            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available") && flightHotel.equalsIgnoreCase("Not Available")){
            
                 display.displayImg("C:/UML/hotel/Class/8.jpg");
            }
            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available") && flightHotel.equalsIgnoreCase("Available")){
            
                display.displayImg("C:/UML/hotel/Class/9.jpg");
            }
            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available") && flightHotel.equalsIgnoreCase("Not Available")){
            
                 display.displayImg("C:/UML/hotel/Class/10.jpg");
            }
            else{
                
                 display.displayImg("C:/UML/hotel/Class/11.jpg");
            }
            
        }
    }

//    public void hotelERDiagBuild() {
//        
//        DisplayImage display = new DisplayImage();
//        
//        if(scaleHotel.equalsIgnoreCase("small")){
//        
//            
//           if(restaurantsHotel.equalsIgnoreCase("Available")){
//               
//                display.displayImg("C:/UML/hotel/Class/2.jpg");
//           }
//           else if(restaurantsHotel.equalsIgnoreCase("Not Available")){
//
//                display.displayImg("C:/UML/hotel/Class/4.png");
//           }
//           else{
//               JOptionPane.showMessageDialog(null, "Requirements insufficient for diagram generation",
//                        "Diagram not found", JOptionPane.PLAIN_MESSAGE);
//           }
//               
//        }else if(scaleHotel.equalsIgnoreCase("medium")){
//            
//            if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available")){
//                 
//                display.displayImg("C:/UML/hotel/Class/5.jpg");
//            }
//            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available")){
//            
//                display.displayImg("C:/UML/hotel/Class/6.jpg");
//            }
//            else{
//                 display.displayImg("C:/UML/hotel/Class/4.png");
//            }
//        }else{
//            
//            if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available") && flightHotel.equalsIgnoreCase("Available")){
//                 
//                display.displayImg("C:/UML/hotel/Class/7.jpg");
//            }
//            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Available") && flightHotel.equalsIgnoreCase("Not Available")){
//            
//                 display.displayImg("C:/UML/hotel/Class/8.jpg");
//            }
//            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available") && flightHotel.equalsIgnoreCase("Available")){
//            
//                display.displayImg("C:/UML/hotel/Class/9.jpg");
//            }
//            else if(restaurantsHotel.equalsIgnoreCase("Available") && taxiHotel.equalsIgnoreCase("Not Available") && flightHotel.equalsIgnoreCase("Not Available")){
//            
//                 display.displayImg("C:/UML/hotel/Class/10.jpg");
//            }
//            else{
//                
//                 display.displayImg("C:/UML/hotel/Class/11.jpg");
//            }
//    }
}
